### PR TITLE
UGM caching

### PR DESCRIPTION
**Pull request by thet**
caching rework:

- cache ugm().users and ugm().groups instead of ugm(). the ugm instance was constructed in no time, but the calls to users and groups, which returned the whole ldap (search base) tree are the expensive calls.

- use cache settings from ldap properties. theoretically, but it doesn't work. LDAPPlugin.settings or LDAPPlugin.ugm().props only hold the default values, but not what i was changing through the web. @rnix, do you have an idea?

- remove bda.cache based framework and use plone.memoize. mainly, because i'd had to write a custom cache manager to be able to cache abitrary methods. the provided cache manager was tailored to just hold one key and no more. besides, i like the caching decorators from plone.memoize.

- there is one test failure. the cause must be again a side effect, which i don't understand. when i keep the ``cache.rst`` line in ``tests.py``, it fails with that file not found but the other error doesn't occur. strange... @rnix any idea?

### CODE REVIEW

**Comment by thet** [comment]
if we want memcached with plone.memoize: https://github.com/plone/Products.PloneOrg/blob/master/src/Products/PloneOrg/caching.py

**Comment by jensens** [comment]
ad cache ugm().users and ugm().groups: ok, but also only a workaround, we need to solve it, so that not all keys are loaded.

ad remove bda.cache: using plone.memoize sounds good at first. but if it comes to many users you dont want to mix template cache and all the other memoize cache in one memcached. so make sure its possible to have an own memcached configured for ldap.

**Comment by rnixx** [comment]
+1 for keeping the ability for a dedicated cache.

@thet ad settings - i need to take a look

**Comment by thet** [comment]
i see, makes sense. i'd love to see ``bda.cache`` having some default cache decorators, which use themselves a default caching backend adapter, adapting ``self`` from the decorated method. that would be as easy to use as ``plone.memoize`` but give all the flexibility you need.

but for the current deployment, i'll just use the ``thet-all`` branch which includes this fixe and live with these tape-fixed solutions until another project allows refactoring.

**Comment by jensens** [comment]
whats the state here?

**Comment by thet** [comment]
@jensens on hold. this branch works for a client project, but I cannot add more resources to work it out as discussed here. Have to wait for another LDAP project to finance this.

**Comment by thet** [comment]
obsolete. performance improvements are already in master.

**Pull request closed without merging**
